name: couldai_user_app
description: "A social media platform like TikTok built with Flutter."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  video_player: ^2.8.7
  chewie: ^1.8.1
  cached_network_image: ^3.3.1
  flutter_staggered_grid_view: ^0.7.0

flutter:
  uses-material-design: true

  assets:
    - assets/videos/
    - assets/images/